### ISSUE TITLE
Controller triggers not captured

### ISSUE THREAD

**Issue by kaluaabyss** [ThornyFFXI/Crossbar#14]
After successfully loading the plugin, gamepad triggers still function normally in the client -- as I understand they should not pull up the CTRL/ALT hotbars so I assume its not registering the trigger events properly.

The binding menu cannot be started with L2+R2+L1+R1.

Plugin outputs 'DirectInput detected' after loading and I see the crossbar element and can move it with my mouse. I've tried changing the settings.xml file to use dinput.xml with no success.

I'm using the latest HorizonXI, Ashita and Crossbar versions. My device is a Stadia gamepad converted to BT mode.
Issue started many releases ago when I first attempted to use the plugin.

Please let me know if I can provide more information that would be helpful. Thanks!

**Comment by kaluaabyss** [comment]
I saw in another comment that tCrossbar replaced this, I also have same issue with that (tried all three gamepad types). Can repost issue in that repo if preferred.

**Comment by ThornyFFXI** [comment]
It is recommended that you use tCrossBar, available here, instead of Crossbar:
https://github.com/ThornyFFXI/tCrossBar

The controller hooks have been drastically improved as of Ashita 4.15, and tCrossBar utilizes those.  There is no plan to continue development of CrossBar, as the hooking method it uses is less optimal than the one built into Ashita.

That said, the most likely issue is that the stadia gamepad is not reporting the triggers in the way that any of the profiles expect.  If you would like to join the Ashita discord during daytime hours, I can likely work with you to create a controller profile that will fit the Stadia correctly.
