### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by DrZapper112** [ThornyFFXI/Crossbar#2]
Hello, your crossbar plugin sounds amazing, but I can't for the life of me get it to load. The crossbar.dll is in the plugin folder and crossbar folder is in the resources folder all inside the ashita directory. When I try to load it I get this error "Failed to load plugin crossbar.dll. Plugin is missing one or more export functions. What am I doing wrong? Any help would be amazing. Thanks

**Comment by Aerres** [comment]
Were you able to get this fixed? If so I'd love to know how

**Comment by ThornyFFXI** [comment]
This issue is caused by either missing required redistributables or using the wrong version of Ashita.  Crossbar only works with Ashita4, so if you're using Ashita3 you cannot use it.  If you are using Ashita4, type '/aver' and make sure to download a release that has the same interface version as your Ashita installation.  If you need further support, you can join Ashita's discord, but this is not an issue with the plugin itself.    Please refrain from making any further comments on closed issues.

**Comment by DrZapper112** [comment]
The plugin is for ashita v4 and I was attempting to use it on v3.
