### ISSUE TITLE
Plugin fails to load

### ISSUE THREAD

**Issue by sarca571ca** [ThornyFFXI/Crossbar#3]
I get 'Failed to load plugin crossbar.dll. Plugin is missing one or more export functions.' when trying to load the plugin. I'm using Linux so I'm guessing that I'm missing a VS redistributable. Would you be able to let me know which one's I require? I've installed 2012 and 2013 already but still the same error.

**Comment by ThornyFFXI** [comment]
There's no official Linux support for Ashita or it's plugins, but crossbar is built with vs2022 so you should need the 2015-2022 redistributable.  If that's not enough to solve your problem, consider joining Ashita discord to spitball ideas.

**Comment by Aerres** [comment]
I am having this same issue on Win 10

**Comment by ThornyFFXI** [comment]
This issue is caused by either missing required redistributables or using the wrong version of Ashita.  Crossbar only works with Ashita4, so if you're using Ashita3 you cannot use it.  If you are using Ashita4, type '/aver' and make sure to download a release that has the same interface version as your Ashita installation.  If you need further support, you can join Ashita's discord, but this is not an issue with the plugin itself.    Please refrain from making any further comments on closed issues.
